// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABTmXtICt8KukmsIDK7ZsOzMm0Lt-F_E4',
    appId: '1:665114855529:web:a46499232cbaa2ea587af8',
    messagingSenderId: '665114855529',
    projectId: 'flutter-chat-app-a148a',
    authDomain: 'flutter-chat-app-a148a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a148a.firebasestorage.app',
    measurementId: 'G-1Y01N0832Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCff_RphmNGIPxINUyz2Zo7RLiOHgaJ0PA',
    appId: '1:665114855529:android:705a2522eb1565cb587af8',
    messagingSenderId: '665114855529',
    projectId: 'flutter-chat-app-a148a',
    storageBucket: 'flutter-chat-app-a148a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANWbK6UN6UO1WCxLc1gRX182HDJEFX6_Q',
    appId: '1:665114855529:ios:8c7625b9e1137ded587af8',
    messagingSenderId: '665114855529',
    projectId: 'flutter-chat-app-a148a',
    storageBucket: 'flutter-chat-app-a148a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANWbK6UN6UO1WCxLc1gRX182HDJEFX6_Q',
    appId: '1:665114855529:ios:8c7625b9e1137ded587af8',
    messagingSenderId: '665114855529',
    projectId: 'flutter-chat-app-a148a',
    storageBucket: 'flutter-chat-app-a148a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABTmXtICt8KukmsIDK7ZsOzMm0Lt-F_E4',
    appId: '1:665114855529:web:f3ecbd18332baae5587af8',
    messagingSenderId: '665114855529',
    projectId: 'flutter-chat-app-a148a',
    authDomain: 'flutter-chat-app-a148a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a148a.firebasestorage.app',
    measurementId: 'G-7WGN1TYK19',
  );
}
